apiVersion: v1
kind: Service
metadata:
  name: eureka-app
spec:
  selector:
    app: eureka-service
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 2
  template: 
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: hari505/microservices-eureka-service:1.0-SNAPSHOT



